# Docker compose version
version: '3'

# define network name
networks:
    symfony:

# images used for our app
services:
    nginx: 
        # using alpine images because it's light 
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            # map local port 8080 to container port 80
            # TODO: change port
            - '8080:80'
        volumes:
            # use app folder as /var/www
            - ./api:/var/www
            # use nginx/default.conf as container nginx default conf
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            # will start php and mysql service before starting
            - php            
        networks: 
            - symfony    

    php:
        image: php:7.2-fpm-alpine
        container_name: php
        volumes:
            - ./api:/var/www
        working_dir: /var/www
        ports:
            - '9091:9000'
        environment:
            PHP_MEMORY_LIMIT: 1G
            # Symfony
            APP_ENV: dev
            APP_SECRET: 7d41a4acde33432b1d51eae15a301550
            # mysql://db_user:db_password@127.0.0.1:3306/db_name
            # DATABASE_URL: mysql://root:root@mysql:3306/symfony_docker
            # MAILER_URL: null://localhost
        networks:
            - symfony

            